var init_data ={
    "TC1001":{"name":"单笔代收","data":{
    	"mer_viral_acct":"",
    	"agrt_no":"",
    	"bank_name":"中国民生银行",
    	"account_no":"6226223300376434",
		"account_name ":"张一",		
		"account_type":"00",
		"brach_bank_province":"",
		"brach_bank_city":"",
		"brach_bank_name":"",
		"tran_amt":"1.00",
		"currency":"CNY",
		"bsn_code":"11203",
		"cert_type":"01",
		"cert_no":"330802198508230915",
		"mobile":"",
		"remark":"代收测试",
		"reserve":""
		}
	},
	"TC2001":{"name":"单笔代收查询","data":{
		"ori_tran_flowid":""
		}
	},
	"TC1002":{"name":"单笔代付","data":{
		"mer_viral_acct":"",
    	"agrt_no":"",
    	"bank_name":"中国民生银行",
    	"account_no":"6226223300376434",
		"account_name ":"张一",		
		"account_type":"00",
		"brach_bank_province":"上海",
		"brach_bank_city":"上海",
		"brach_bank_name":"",
		"tran_amt":"1.00",
		"currency":"CNY",
		"bsn_code":"11203",
		"cert_type":"01",
		"cert_no":"",
		"mobile":"",
		"remark":"代付测试",
		"reserve":""
		}
	},
	"TC2002":{"name":"代付查询","data":{
		"ori_tran_flowid":""
		}
	}
};